alter table public.posts add column author_id uuid references public.users(id) on delete set null;
alter table public.posts add column likes_count integer not null default 0;

create table public.comments (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  user_id uuid not null references public.users(id) on delete cascade,
  comment_text text not null,
  created_at timestamptz not null default current_timestamp
);

create index comments_post_id_idx on public.comments (post_id);
create index comments_user_id_idx on public.comments (user_id);

create table public.likes (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  user_id uuid not null references public.users(id) on delete cascade,
  liked_at timestamptz not null default current_timestamp,
  unique (post_id, user_id)
);

create index likes_post_id_idx on public.likes (post_id);
create index likes_user_id_idx on public.likes (user_id);

create or replace function public.adjust_post_likes_count()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if TG_OP = 'INSERT' then
    update public.posts set likes_count = likes_count + 1 where id = new.post_id;
    return new;
  elsif TG_OP = 'DELETE' then
    update public.posts set likes_count = likes_count - 1 where id = old.post_id;
    return old;
  end if;
  return null;
end;
$$;

create trigger likes_adjust_post_count
after insert or delete on public.likes
for each row execute function public.adjust_post_likes_count();

alter table public.comments enable row level security;
alter table public.likes enable row level security;

grant select, insert, update, delete on public.comments to service_role;
grant select, insert, update, delete on public.likes to service_role;
grant usage, select on all sequences in schema public to service_role;
