create table public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  slug text not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.posts (
  id bigint generated by default as identity primary key,
  category_id bigint not null references public.categories(id) on delete restrict,
  artist text,
  best_pick text,
  spotify_url text,
  image_url text not null,
  detail_image_url text,
  detail_image_position text not null default 'center',
  title text not null,
  description text not null,
  content text not null,
  status text not null default 'draft' check (status in ('draft', 'published')),
  author_name text not null default 'Techin B.',
  author_avatar_url text,
  author_bio text[] not null default '{}',
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index posts_status_published_at_idx
  on public.posts (status, published_at desc);

create index posts_category_id_idx
  on public.posts (category_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger categories_set_updated_at
before update on public.categories
for each row execute function public.set_updated_at();

create trigger posts_set_updated_at
before update on public.posts
for each row execute function public.set_updated_at();

alter table public.categories enable row level security;
alter table public.posts enable row level security;

grant usage on schema public to service_role;
grant select, insert, update, delete on public.categories to service_role;
grant select, insert, update, delete on public.posts to service_role;
grant usage, select on all sequences in schema public to service_role;
